version: 2
updates:
  # Default branch (maintenance-3.1.x)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "maintenance-3.1.x"
    reviewers:
      - "nuxeo/ui"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      gha:
        patterns:
          - "*"

  # LTS-2025 branch
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "lts-2025"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[lts-2025]"
    labels:
      - "dependencies"
      - "lts-2025"
    reviewers:
      - "nuxeo/ui"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "lts-2025"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[lts-2025]"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      gha:
        patterns:
          - "*"