import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export default {
  stories: ['../src/elements/**/*.stories.js'],
  staticDirs: ['../public'],
  framework: {
    name: '@storybook/web-components-vite',
    options: {},
  },
  viteFinal: async (config) => {
    config.resolve = config.resolve || {};
    config.resolve.alias = config.resolve.alias || {};
    // Resolve analysis.json from the local ui package (generated by polymer analyze)
    config.resolve.alias['@nuxeo/nuxeo-ui-elements/analysis.json'] = resolve(__dirname, '../../ui/analysis.json');
    return config;
  },
};
