name: Cleanup

on:
  pull_request:
    types: [closed, unlabeled]
    branches:
      - lts-2025

permissions:
  contents: read

jobs:
  webui-cleanup:
    runs-on: ubuntu-latest
    if: (github.event.action == 'unlabeled' && github.event.label.name == 'webui-preview') || contains(github.event.pull_request.labels.*.name, 'webui-preview')
    steps:
      - uses: actions/checkout@v6

      - name: Prepare environment
        run: |
          echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV

      - name: Web UI preview
        uses: nuxeo/ui-team-gh-actions/trigger-workflow@a5b89f35e0d1f3a912f528d7f1c3acdb73c60549
        with:
          owner: nuxeo
          repo: nuxeo-web-ui
          workflow-id: clean.yaml
          access-token: ${{ secrets.GIT_ADMIN_TOKEN }}
          branch-name: lts-2025
          inputs: |
            branch_name: ${{ env.BRANCH_NAME }}
