name: Web UI

on:
  pull_request:
    branches:
      - maintenance-3.1.x
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: maintenance-3.1.x
        type: string
        required: false

permissions:
  contents: read

jobs:
  web-ui:
    uses: nuxeo/nuxeo-web-ui/.github/workflows/cross-repo.yaml@maintenance-3.1.x
    with:
      branch_name: ${{ github.head_ref || inputs.branch || 'maintenance-3.1.x' }}
      sauce_labs: false
      skip_ftests: false
      skip_a11y: false
      skip_unit_tests: false
      generate_metrics: false
      run_all: false
      bail: 0