name: Lint

on:
  pull_request:
    branches:
      - maintenance-3.1.x
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: maintenance-3.1.x
        type: string
        required: false
    secrets:
      NEXUS_NPM_USERNAME:
        required: true
      NEXUS_NPM_PASSWORD:
        required: true

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-3.1.x' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Configure npm for Nexus
        run: |
          cat <<EOF > ~/.npmrc
          registry=https://packages.nuxeo.com/repository/npm-public/
          @nuxeo:registry=https://packages.nuxeo.com/repository/npm-public/
          //packages.nuxeo.com/repository/npm-public/:username=${{ secrets.NEXUS_NPM_USERNAME }}
          //packages.nuxeo.com/repository/npm-public/:password=${{ secrets.NEXUS_NPM_PASSWORD }}
          //packages.nuxeo.com/repository/npm-public/:always-auth=true
          EOF

      - name: Verify Nexus auth
        run: npm whoami --registry=https://packages.nuxeo.com/repository/npm-public/

      - name: Install
        run: |
          npm install --no-package-lock
          npm run bootstrap

      - name: Lint
        run: npm run lint
