name: Storybook

on:
  pull_request:
    branches:
      - lts-2025
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: lts-2025
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true
      GIT_ADMIN_TOKEN:
        description: 'GIT_ADMIN_TOKEN'
        required: false

permissions:
  contents: write

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'lts-2025' }}

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          npm install --no-package-lock
          npm run bootstrap

      - name: Run analysis
        run: npx lerna run analysis --parallel

      - name: Build storybook
        working-directory: storybook
        run: |
          npx storybook build -o dist

      - name: Deploy
        if: ${{ env.BRANCH_NAME == 'lts-2025' }}
        env:
          GH_TOKEN: nuxeo-webui-jx-bot:${{ secrets.GIT_ADMIN_TOKEN }}
        working-directory: storybook
        run: npm run deploy -- --ci --existing-output-dir=dist
