name: Test

on:
  pull_request:
    branches:
      - maintenance-2.4.x
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: maintenance-2.4.x
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true
      SAUCE_ACCESS_KEY:
        description: 'SAUCE_ACCESS_KEY'
        required: true

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-2.4.x' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - run: npm install -g bower

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          bower install
          npm install

      - name: Test
        env:
          SAUCE_USERNAME: nuxeo-elements
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run test