name: Web UI preview

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - maintenance-3.0.x

env:
  DOCKER_REGISTRY: us-east1-docker.pkg.dev
  DOCKER_IMAGE: ${{ secrets.GKE_PROJECT }}/webui/nuxeo-web-ui
  GKE_CLUSTER: jx-prod
  GKE_ZONE: us-east1-b

jobs:
  preview:
    name: Setup
    if: (github.event.action == 'labeled' && github.event.label.name == 'webui-preview') || contains(github.event.pull_request.labels.*.name, 'webui-preview')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
        scope: '@nuxeo'

    - name: Prepare environment
      run: |
        BRANCH_NAME=${GITHUB_HEAD_REF##*/}
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "VERSION=$(npx -c 'echo "$npm_package_version"')-$BRANCH_NAME" >> $GITHUB_ENV
        echo "PREVIEW_NAMESPACE=elements-web-ui-$(echo $BRANCH_NAME | sed 's/[^[:alnum:]-]/-/g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Determine nuxeo-web-ui branch to use
      id: pick_nuxeo_web_ui_branch
      run: |
        if git ls-remote --exit-code --heads https://github.com/nuxeo/nuxeo-web-ui ${GITHUB_HEAD_REF}; then
          echo ::set-output name=branch::${GITHUB_HEAD_REF}
        else
          echo ::set-output name=branch::maintenance-3.0.x
        fi

    - name: Checkout the nuxeo-web-ui repo
      uses: actions/checkout@v2
      with:
        repository: nuxeo/nuxeo-web-ui
        path: nuxeo-web-ui
        fetch-depth: 1
        ref: ${{ steps.pick_nuxeo_web_ui_branch.outputs.branch }}

    - name: Pack Elements modules
      run: |
        pushd core
        echo "ELEMENTS_CORE=$(npm pack 2>&1 | tail -1)" >> $GITHUB_ENV
        popd

        pushd ui
        echo "ELEMENTS_UI=$(npm pack 2>&1 | tail -1)" >> $GITHUB_ENV
        popd

        pushd dataviz
        echo "ELEMENTS_DATAVIZ=$(npm pack 2>&1 | tail -1)" >> $GITHUB_ENV
        popd

    - name: Install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        pushd nuxeo-web-ui
        npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" ../core/${ELEMENTS_CORE}
        npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" ../ui/${ELEMENTS_UI}
        npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" ../dataviz/${ELEMENTS_DATAVIZ}
        npm install
        popd

    - name: Webpack build
      run: |
        pushd nuxeo-web-ui
        npm run build
        popd

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: _json_key
        password: ${{ secrets.GKE_SA_KEY }}

    - name: Build and push server image
      uses: docker/build-push-action@v2
      with:
        context: nuxeo-web-ui/server
        pull: true
        push: true
        file: nuxeo-web-ui/server/Dockerfile
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}/server:${{ env.VERSION }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: nuxeo-web-ui
        pull: true
        push: true
        file: nuxeo-web-ui/Dockerfile
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
        build-args: SERVER_IMAGE=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}/server:${{ env.VERSION }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Check preview namespace
      id: preview_ns
      run: |
        echo ::set-output name=exists::$(kubectl get namespace ${PREVIEW_NAMESPACE})

    - name: Create preview namespace
      if: ${{ !steps.preview_ns.outputs.exists }}
      run: |
        kubectl create namespace ${PREVIEW_NAMESPACE}

    - name: Install preview
      id: preview
      working-directory: ./nuxeo-web-ui/charts/preview
      run: |
        # add helm jx repo
        helm repo add jx https://jenkins-x-charts.github.io/v2/

        # substitute env variables in values.yaml
        mv values.yaml values.yaml.tosubst
        envsubst < values.yaml.tosubst > values.yaml

        # update helm deps
        helm dependency update .

        # install
        helm upgrade --install --namespace ${PREVIEW_NAMESPACE} ${PREVIEW_NAMESPACE} .

        # ensure the deployment is restarted to pull the new preview image
        kubectl rollout restart deployment ${PREVIEW_NAMESPACE}-preview --namespace ${PREVIEW_NAMESPACE}
        
        echo "PREVIEW_URL=https://preview-${PREVIEW_NAMESPACE}.webui.dev.nuxeo.com" >> $GITHUB_ENV

    - uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `:star: Web UI preview available [here](${process.env.PREVIEW_URL})`
          })
